/**
 * ColdBox config for the top-level test app.
 *
 * Filename must be Coldbox.cfc (convention is config.Coldbox). Linux is
 * case-sensitive; ColdBox.cfc is not found and the default Settings.cfc loads.
 *
 * This module is loaded like a host app would load it: tests/modules/listmonk
 * (symlink to the checkout). Empty include means all conventional modules.
 *
 * Listmonk URL/user/token come from tests/docker/creds/api.json.env (written on
 * first `docker compose --project-directory tests/docker up`).
 */
component {

	function configure() {
		coldbox = {
			appName                 : "listmonk-tests",
			reinitPassword          : "",
			handlersIndexAutoReload : true,
			handlerCaching          : false,
			eventCaching            : false
		};

		environments = {
			development : "localhost,127\\.0\\.0\\.1"
		};

		modules = {
			include : [],
			exclude : []
		};

		interceptors = [];

		var creds = loadListmonkCreds();

		moduleSettings = {
			listmonk : {
				baseUrl           : creds.LISTMONK_URL,
				apiUser           : creds.LISTMONK_API_USER,
				apiToken          : creds.LISTMONK_API_TOKEN,
				timeout           : 5,
				subscriberMode    : "fallback",
				contentType       : "html",
				defaultTemplateId : 0
			}
		};
	}

	/**
	 * Loads credentials for the "main API user", which are
	 * expected to have been auto-generated by the listmonk
	 * docker container when it first starts.
	 * See Dockerfile for details.
	 */
	private struct function loadListmonkCreds() {
		var credsPath = expandPath(
			getDirectoryFromPath( getMetadata( this ).path ) & "/../docker/creds/api.json.env"
		);
		if ( !fileExists( credsPath ) ) {
			throw(
				type    = "ListmonkTest.MissingCreds",
				message = "Listmonk test credentials not found at #credsPath#. Start the test server: docker compose --project-directory tests/docker up -d"
			);
		}

		var creds = deserializeJSON( fileRead( credsPath ) );
		for ( var key in [ "LISTMONK_URL", "LISTMONK_API_USER", "LISTMONK_API_TOKEN" ] ) {
			if ( !creds.keyExists( key ) || !len( creds[ key ] ) ) {
				throw(
					type    = "ListmonkTest.MissingCreds",
					message = "tests/docker/creds/api.json.env is missing #key#"
				);
			}
		}
		return creds;
	}

}
